language: python
python:
  - '3.6'
env:
  matrix:
    - TOXENV=py36-django-111
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$HOME/.wheels
branches:
  only:
  - master
before_script:
  - pip freeze
install:
    - mkdir -p $PIP_WHEEL_DIR
    - pip install -U pip
    - pip wheel coveralls tox
    - pip install coveralls tox
    - pip install -r dev-requirements.txt
script:
  - tox -e $TOXENV
