language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$HOME/.wheels
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34-django-18
      env: TOXENV=py34-django-19
      env: TOXENV=py34-django-110
    - python: 3.5
      env: TOXENV=py35-django-18
      env: TOXENV=py35-django-19
      env: TOXENV=py35-django-110
    - python: 3.6
      env: TOXENV=py36-django-111
branches:
  only:
  - master
before_script:
  - pip freeze
install:
    - mkdir -p $PIP_WHEEL_DIR
    - pip install -U pip
    - pip wheel coveralls tox
    - pip install coveralls tox
    - pip install -r dev-requirements.txt
script:
  - tox -e $TOXENV
