sudo: required
addons:
  chrome: stable
language: python
python:
  - '3.6'
env:
  matrix:
    - TOXENV=py36-django-111-bs3
    - TOXENV=py36-django-111-bs4
    - TOXENV=py36-django-20-bs3
    - TOXENV=py36-django-20-bs4
    - TOXENV=py36-django-21-bs3
    - TOXENV=py36-django-21-bs4
    - TOXENV=py36-django-22-bs3
    - TOXENV=py36-django-22-bs4
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$HOME/.wheels
branches:
  only:
  - master
before_script:
  - pip freeze
install:
    - PATH=$PATH:$HOME
    - CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
    - wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - chmod 0755 ~/chromedriver
    - mkdir -p $PIP_WHEEL_DIR
    - pip install -U pip
    - pip wheel coveralls tox
    - pip install coveralls tox
    - pip install -r dev-requirements.txt
script:
  - tox -e $TOXENV
