version: 2
jobs:
  test:
    docker:
    - image: circleci/python:latest-browsers
    environment:
      CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: |
          git clone https://github.com/pyenv/pyenv.git ~/.pyenv
	  export PYENV_ROOT="$HOME/.pyenv"
	  export PATH="$PYENV_ROOT/bin:$PATH"
	  pyenv init -
	  pyenv install 3.6.4
          $(pyenv root)/versions/3.6.4/bin/python --version
          # https://stackoverflow.com/questions/27849412/permissionerror-with-pip3
          $(pyenv root)/versions/3.6.4/bin/python -m pip install -U pip wheel tox tox-pyenv setuptools --user
          $(pyenv root)/versions/3.6.4/bin/python -m tox -r -e py36-django-111
workflows:
  version: 2
  all_steps:
    jobs:
      - test

