version: 2

executors:
  py-latest-executor:
    docker:
      - image: circleci/python:latest-browsers
    environment:
      CHROME_BIN: "/usr/bin/google-chrome"

jobs:
  "checkout_code":
    executor: py-latest-executor
    steps:
      - checkout
      - run: |
          # Install pyenv to use exact version of Python.
          git clone https://github.com/pyenv/pyenv.git ~/.pyenv
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          pyenv init -
          pyenv install 3.7.0
          echo Version of Python installed in the python:latest-browsers image.
          python3 --version
          export PATH="$(pyenv root)/versions/3.7.0/bin/:$PATH"
          echo Version of Python used to run the tests.
          python3 --version
          # https://stackoverflow.com/questions/27849412/permissionerror-with-pip3
          python3 -m pip install -U pip wheel tox tox-pyenv setuptools --user
  "bootstrap3":
    executor: py-latest-executor
    steps:
      - run: |
          python3 -m tox -r -e py37-django-21-bs3
  "bootstrap4":
    executor: py-latest-executor
    steps:
      - run: |
          python3 -m tox -r -e py37-django-21-bs4
workflows:
  version: 2
  all_steps:
    jobs:
      - "checkout_code"
      - "bootstrap3":
          requires:
            - "checkout_code"
      - "bootstrap4":
          requires:
            - "checkout_code"
