version: 2
jobs:
  "bootstrap3":
    docker:
    - image: circleci/python:latest-browsers
    environment:
      CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: |
          .circleci/env.sh
          python3 -m tox -r -e py37-django-21-bs3
  "bootstrap4":
    docker:
    - image: circleci/python:latest-browsers
    environment:
      CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - run: |
          .circleci/env.sh
          python3 -m tox -r -e py37-django-21-bs4
workflows:
  version: 2
  all_steps:
    jobs:
      - "bootstrap3"
      - "bootstrap4"
